"""
Run once to populate the database with sample restaurant data.
Usage:
    python seed.py          # 기존 데이터 있으면 스킵
    python seed.py --force  # 기존 데이터 삭제 후 재시딩
"""

import sys
import os

sys.path.insert(0, os.path.dirname(__file__))

from app.db.base import Base
from app.db.session import engine, SessionLocal
from app.models.restaurant import Restaurant

SEED_RESTAURANTS = [
    # ── 한식 (35) ────────────────────────────────────────────────────────────
    {
        "name": "한옥 그릴",
        "category": "Korean",
        "address": "서울 종로구 인사동길 12",
        "latitude": 37.5744, "longitude": 126.9858,
        "price_range": 2, "rating": 4.5,
        "description": "아늑한 한옥 공간에서 즐기는 전통 한국식 BBQ. 로맨틱한 저녁 식사에 제격입니다.",
        "phone": "02-1234-5678",
    },
    {
        "name": "명동 닭갈비",
        "category": "Korean",
        "address": "서울 중구 명동2가",
        "latitude": 37.5633, "longitude": 126.9852,
        "price_range": 1, "rating": 4.2,
        "description": "야채와 함께 볶은 매콤한 닭갈비. 부담 없이 즐기기 좋은 데이트 메뉴입니다.",
        "phone": "02-2345-6789",
    },
    {
        "name": "북촌 삼겹살",
        "category": "Korean",
        "address": "서울 종로구 북촌로 5",
        "latitude": 37.5815, "longitude": 126.9848,
        "price_range": 2, "rating": 4.3,
        "description": "프리미엄 삼겹살과 수제 막걸리 페어링. 북촌의 정취를 느낄 수 있는 곳입니다.",
        "phone": "02-3456-7890",
    },
    {
        "name": "서울 갈비하우스",
        "category": "Korean",
        "address": "서울 강남구 강남대로 123",
        "latitude": 37.4979, "longitude": 127.0276,
        "price_range": 3, "rating": 4.7,
        "description": "고급 한우 갈비와 프리미엄 부위를 제공하는 특별한 날을 위한 레스토랑.",
        "phone": "02-4567-8901",
    },
    {
        "name": "종로 설렁탕",
        "category": "Korean",
        "address": "서울 종로구 종로 144",
        "latitude": 37.5703, "longitude": 126.9920,
        "price_range": 1, "rating": 4.4,
        "description": "수십 년 전통의 진한 사골 국물 설렁탕. 든든한 한 끼로 손색이 없습니다.",
        "phone": "02-5678-1234",
    },
    {
        "name": "을지로 순대국밥",
        "category": "Korean",
        "address": "서울 중구 을지로3가 310",
        "latitude": 37.5662, "longitude": 126.9937,
        "price_range": 1, "rating": 4.1,
        "description": "구수하고 진한 순대국밥 전문점. 회식과 해장에 인기 만점입니다.",
        "phone": "02-2267-3344",
    },
    {
        "name": "신촌 닭한마리",
        "category": "Korean",
        "address": "서울 서대문구 신촌로 81",
        "latitude": 37.5559, "longitude": 126.9368,
        "price_range": 2, "rating": 4.3,
        "description": "신선한 닭을 통째로 끓인 닭한마리 전문점. 칼국수와 함께 즐기세요.",
        "phone": "02-393-5577",
    },
    {
        "name": "홍대 원조 떡볶이",
        "category": "Korean",
        "address": "서울 마포구 어울마당로 56",
        "latitude": 37.5572, "longitude": 126.9240,
        "price_range": 1, "rating": 4.0,
        "description": "홍대 골목의 명물 즉석 떡볶이. 순대, 튀김과 함께 즐기는 분식의 정석.",
        "phone": "02-322-7788",
    },
    {
        "name": "마포 갈치조림",
        "category": "Korean",
        "address": "서울 마포구 마포대로 45",
        "latitude": 37.5500, "longitude": 126.9494,
        "price_range": 2, "rating": 4.5,
        "description": "매콤달콤한 양념으로 조린 생갈치. 밥도둑이 따로 없는 반찬 반찬 밥상.",
        "phone": "02-713-2299",
    },
    {
        "name": "합정 쭈꾸미볶음",
        "category": "Korean",
        "address": "서울 마포구 양화로 133",
        "latitude": 37.5497, "longitude": 126.9140,
        "price_range": 1, "rating": 4.2,
        "description": "불맛 가득한 쭈꾸미볶음. 삼겹살과 곁들여 먹으면 더욱 맛있습니다.",
        "phone": "02-334-6655",
    },
    {
        "name": "망원 돼지갈비",
        "category": "Korean",
        "address": "서울 마포구 망원동 388",
        "latitude": 37.5556, "longitude": 126.9049,
        "price_range": 2, "rating": 4.3,
        "description": "두툼하게 썰어 숯불에 구운 돼지갈비. 동네 주민들의 단골 맛집.",
        "phone": "02-332-9900",
    },
    {
        "name": "상수 생선구이",
        "category": "Korean",
        "address": "서울 마포구 토정로 132",
        "latitude": 37.5480, "longitude": 126.9220,
        "price_range": 2, "rating": 4.4,
        "description": "제철 생선을 구워 내는 생선구이 전문점. 고등어, 갈치, 조기 등 다양하게.",
        "phone": "02-325-4433",
    },
    {
        "name": "성수 육회비빔밥",
        "category": "Korean",
        "address": "서울 성동구 성수이로 52",
        "latitude": 37.5444, "longitude": 127.0557,
        "price_range": 2, "rating": 4.6,
        "description": "신선한 한우 육회 위에 오색 나물을 올린 육회비빔밥. 성수의 숨은 맛집.",
        "phone": "02-461-2277",
    },
    {
        "name": "건대 치킨호프",
        "category": "Korean",
        "address": "서울 광진구 능동로 183",
        "latitude": 37.5404, "longitude": 127.0705,
        "price_range": 1, "rating": 4.0,
        "description": "바삭하게 튀긴 황금빛 치킨과 시원한 생맥주. 건대 대표 야식 명소.",
        "phone": "02-445-8833",
    },
    {
        "name": "잠실 불고기",
        "category": "Korean",
        "address": "서울 송파구 올림픽로 269",
        "latitude": 37.5133, "longitude": 127.1028,
        "price_range": 2, "rating": 4.3,
        "description": "달콤 짭조름한 양념으로 재운 한우 불고기. 가족 외식 장소로 제격.",
        "phone": "02-412-5566",
    },
    {
        "name": "강남 낙곱새",
        "category": "Korean",
        "address": "서울 강남구 역삼동 814",
        "latitude": 37.5000, "longitude": 127.0360,
        "price_range": 2, "rating": 4.5,
        "description": "낙지, 곱창, 새우를 한 번에 즐기는 낙곱새 전문점. 매운 맛이 일품.",
        "phone": "02-567-4411",
    },
    {
        "name": "청담 한우 전문",
        "category": "Korean",
        "address": "서울 강남구 청담동 101",
        "latitude": 37.5210, "longitude": 127.0460,
        "price_range": 3, "rating": 4.8,
        "description": "1++ 등급 한우만 엄선해 제공하는 프리미엄 한우 레스토랑. 특별한 날에 추천.",
        "phone": "02-549-7788",
    },
    {
        "name": "압구정 참치",
        "category": "Korean",
        "address": "서울 강남구 압구정로 332",
        "latitude": 37.5270, "longitude": 127.0285,
        "price_range": 3, "rating": 4.6,
        "description": "참다랑어 직배송으로 매일 신선한 참치회를 제공. 최고급 참치 오마카세.",
        "phone": "02-546-3399",
    },
    {
        "name": "역삼 해장국",
        "category": "Korean",
        "address": "서울 강남구 역삼로 152",
        "latitude": 37.5000, "longitude": 127.0360,
        "price_range": 1, "rating": 4.2,
        "description": "진한 선지해장국으로 유명한 24시간 운영 해장국집. 속이 든든해집니다.",
        "phone": "02-554-2211",
    },
    {
        "name": "선릉 된장찌개",
        "category": "Korean",
        "address": "서울 강남구 선릉로 428",
        "latitude": 37.5030, "longitude": 127.0490,
        "price_range": 1, "rating": 4.3,
        "description": "직접 담근 된장으로 끓인 구수한 된장찌개. 직장인 점심 맛집.",
        "phone": "02-565-1133",
    },
    {
        "name": "논현 장어구이",
        "category": "Korean",
        "address": "서울 강남구 논현로 712",
        "latitude": 37.5110, "longitude": 127.0300,
        "price_range": 3, "rating": 4.5,
        "description": "살아있는 민물장어를 그 자리에서 손질해 구워 드리는 장어구이 전문점.",
        "phone": "02-545-8844",
    },
    {
        "name": "방배 보쌈",
        "category": "Korean",
        "address": "서울 서초구 방배로 143",
        "latitude": 37.4810, "longitude": 126.9980,
        "price_range": 2, "rating": 4.4,
        "description": "촉촉하게 삶은 보쌈과 새우젓, 김치의 조화. 생막걸리와 환상의 궁합.",
        "phone": "02-596-7722",
    },
    {
        "name": "동작 냉면",
        "category": "Korean",
        "address": "서울 동작구 동작대로 133",
        "latitude": 37.5100, "longitude": 126.9400,
        "price_range": 1, "rating": 4.3,
        "description": "평양식 물냉면과 함흥식 비빔냉면 모두 제공. 여름철 필수 방문 맛집.",
        "phone": "02-825-4466",
    },
    {
        "name": "여의도 대게구이",
        "category": "Korean",
        "address": "서울 영등포구 여의대방로 290",
        "latitude": 37.5217, "longitude": 126.9244,
        "price_range": 3, "rating": 4.6,
        "description": "영덕 대게를 직송받아 즉석에서 구워 드리는 대게구이 전문점.",
        "phone": "02-782-5599",
    },
    {
        "name": "영등포 돼지국밥",
        "category": "Korean",
        "address": "서울 영등포구 영등포로 77",
        "latitude": 37.5260, "longitude": 126.8960,
        "price_range": 1, "rating": 4.1,
        "description": "부산식 돼지국밥의 서울 대표 맛집. 진한 뼈 육수가 일품입니다.",
        "phone": "02-633-3311",
    },
    {
        "name": "노량진 수산물",
        "category": "Korean",
        "address": "서울 동작구 노량진로 121",
        "latitude": 37.5140, "longitude": 126.9430,
        "price_range": 2, "rating": 4.5,
        "description": "노량진 수산시장 직배송 활어회. 싱싱한 회와 각종 해산물을 합리적인 가격에.",
        "phone": "02-813-7755",
    },
    {
        "name": "이태원 순두부찌개",
        "category": "Korean",
        "address": "서울 용산구 이태원로 234",
        "latitude": 37.5350, "longitude": 126.9940,
        "price_range": 1, "rating": 4.2,
        "description": "부드러운 순두부에 해산물과 채소를 넣은 얼큰한 순두부찌개 전문점.",
        "phone": "02-792-6644",
    },
    {
        "name": "혜화 닭볶음탕",
        "category": "Korean",
        "address": "서울 종로구 혜화로 35",
        "latitude": 37.5823, "longitude": 127.0019,
        "price_range": 2, "rating": 4.3,
        "description": "매콤하게 졸인 닭볶음탕. 대학로 연극 관람 전후 인기 있는 맛집.",
        "phone": "02-763-2288",
    },
    {
        "name": "인사동 쌈밥집",
        "category": "Korean",
        "address": "서울 종로구 인사동10길 22",
        "latitude": 37.5740, "longitude": 126.9860,
        "price_range": 2, "rating": 4.4,
        "description": "10가지 이상의 쌈 채소와 다양한 나물, 된장에 즐기는 전통 쌈밥.",
        "phone": "02-732-4411",
    },
    {
        "name": "광화문 설렁탕",
        "category": "Korean",
        "address": "서울 종로구 세종대로 149",
        "latitude": 37.5710, "longitude": 126.9770,
        "price_range": 1, "rating": 4.3,
        "description": "광화문 인근 직장인들의 점심 명소. 맑고 진한 설렁탕 국물이 일품.",
        "phone": "02-723-9900",
    },
    {
        "name": "동대문 곱창",
        "category": "Korean",
        "address": "서울 중구 을지로42가길 33",
        "latitude": 37.5670, "longitude": 127.0090,
        "price_range": 2, "rating": 4.4,
        "description": "신선한 소곱창을 연탄불에 구워 먹는 동대문 전통 곱창 골목 명가.",
        "phone": "02-2265-7788",
    },
    {
        "name": "신림 부대찌개",
        "category": "Korean",
        "address": "서울 관악구 신림로 315",
        "latitude": 37.4840, "longitude": 126.9290,
        "price_range": 1, "rating": 4.1,
        "description": "햄, 소시지, 김치가 어우러진 푸짐한 부대찌개. 라면 추가 필수!",
        "phone": "02-872-5533",
    },
    {
        "name": "대학로 닭갈비",
        "category": "Korean",
        "address": "서울 종로구 대학로 104",
        "latitude": 37.5820, "longitude": 127.0010,
        "price_range": 1, "rating": 4.2,
        "description": "철판에 볶아 먹는 매콤한 닭갈비. 공연 관람 전후 대학로 대표 맛집.",
        "phone": "02-766-3388",
    },
    {
        "name": "목동 갈비",
        "category": "Korean",
        "address": "서울 양천구 목동로 293",
        "latitude": 37.5270, "longitude": 126.8750,
        "price_range": 2, "rating": 4.3,
        "description": "목동 주민들의 오래된 단골 갈비집. 양념갈비와 생갈비 모두 훌륭.",
        "phone": "02-655-4422",
    },
    {
        "name": "왕십리 곱창",
        "category": "Korean",
        "address": "서울 성동구 왕십리로 185",
        "latitude": 37.5620, "longitude": 127.0280,
        "price_range": 2, "rating": 4.4,
        "description": "왕십리 곱창거리의 터줏대감. 막창, 대창, 소장 모두 맛볼 수 있습니다.",
        "phone": "02-2296-6611",
    },

    # ── 일식 (15) ────────────────────────────────────────────────────────────
    {
        "name": "사쿠라 오마카세",
        "category": "Japanese",
        "address": "서울 강남구 청담동 88",
        "latitude": 37.5203, "longitude": 127.0474,
        "price_range": 3, "rating": 4.8,
        "description": "셰프가 엄선한 오마카세 코스. 예약 필수이며 최상의 스시 경험을 제공합니다.",
        "phone": "02-5678-9012",
    },
    {
        "name": "라멘 리퍼블릭",
        "category": "Japanese",
        "address": "서울 마포구 홍대로 15",
        "latitude": 37.5572, "longitude": 126.9244,
        "price_range": 1, "rating": 4.4,
        "description": "진한 돈코츠와 쇼유 라멘. 아늑한 카운터 자리에서 혼자 또는 둘이 즐기기 좋습니다.",
        "phone": "02-6789-0123",
    },
    {
        "name": "이자카야 요루",
        "category": "Japanese",
        "address": "서울 용산구 이태원로 27",
        "latitude": 37.5340, "longitude": 126.9941,
        "price_range": 2, "rating": 4.3,
        "description": "수제 칵테일과 다양한 안주를 즐길 수 있는 일본식 이자카야.",
        "phone": "02-7890-1234",
    },
    {
        "name": "신사 스시바",
        "category": "Japanese",
        "address": "서울 강남구 압구정로 179",
        "latitude": 37.5220, "longitude": 127.0200,
        "price_range": 3, "rating": 4.7,
        "description": "회전 없이 셰프가 직접 쥐어 주는 에도마에 스시. 가성비 있는 스시 오마카세.",
        "phone": "02-541-7722",
    },
    {
        "name": "홍대 우동",
        "category": "Japanese",
        "address": "서울 마포구 와우산로 57",
        "latitude": 37.5555, "longitude": 126.9260,
        "price_range": 1, "rating": 4.3,
        "description": "수제 면으로 끓인 쫄깃한 우동. 카레우동, 붓카케 등 다양한 종류 제공.",
        "phone": "02-322-8855",
    },
    {
        "name": "성수 라멘",
        "category": "Japanese",
        "address": "서울 성동구 서울숲2길 32",
        "latitude": 37.5445, "longitude": 127.0480,
        "price_range": 1, "rating": 4.4,
        "description": "닭 육수 기반의 담백한 시오 라멘과 진한 된장 라멘. 성수 힙플레이스.",
        "phone": "02-461-9977",
    },
    {
        "name": "이태원 야키니쿠",
        "category": "Japanese",
        "address": "서울 용산구 이태원로 209",
        "latitude": 37.5355, "longitude": 126.9950,
        "price_range": 2, "rating": 4.3,
        "description": "일본식 야키니쿠 전문점. 와규와 다양한 부위를 숯불에 구워 즐깁니다.",
        "phone": "02-795-4433",
    },
    {
        "name": "강남 텐동",
        "category": "Japanese",
        "address": "서울 강남구 테헤란로 123",
        "latitude": 37.5010, "longitude": 127.0330,
        "price_range": 2, "rating": 4.4,
        "description": "바삭한 튀김을 밥 위에 올린 텐동 전문점. 점심 특선이 특히 인기입니다.",
        "phone": "02-558-6622",
    },
    {
        "name": "합정 이자카야",
        "category": "Japanese",
        "address": "서울 마포구 양화로 166",
        "latitude": 37.5500, "longitude": 126.9150,
        "price_range": 2, "rating": 4.2,
        "description": "감각적인 인테리어의 모던 이자카야. 사케 컬렉션이 다양합니다.",
        "phone": "02-336-7744",
    },
    {
        "name": "삼청 소바",
        "category": "Japanese",
        "address": "서울 종로구 삼청로 92",
        "latitude": 37.5840, "longitude": 126.9810,
        "price_range": 2, "rating": 4.5,
        "description": "삼청동 골목의 수제 메밀 소바. 자루소바와 따뜻한 니신소바 모두 인기.",
        "phone": "02-732-5599",
    },
    {
        "name": "종로 돈카츠",
        "category": "Japanese",
        "address": "서울 종로구 인사동5길 44",
        "latitude": 37.5700, "longitude": 126.9870,
        "price_range": 1, "rating": 4.3,
        "description": "두툼하고 바삭한 수제 돈카츠 전문점. 히레카츠와 로스카츠 모두 일품.",
        "phone": "02-734-2244",
    },
    {
        "name": "연남 라멘",
        "category": "Japanese",
        "address": "서울 마포구 연남로 53",
        "latitude": 37.5600, "longitude": 126.9280,
        "price_range": 1, "rating": 4.3,
        "description": "돼지 뼈를 12시간 우린 진한 톤코츠 라멘. 연남동 핫플레이스 라멘집.",
        "phone": "02-334-5511",
    },
    {
        "name": "강남 규동",
        "category": "Japanese",
        "address": "서울 강남구 강남대로 396",
        "latitude": 37.5050, "longitude": 127.0250,
        "price_range": 1, "rating": 4.1,
        "description": "얇게 썬 소고기를 달콤한 간장 소스에 조린 일본식 규동 덮밥.",
        "phone": "02-562-3377",
    },
    {
        "name": "한남 스시",
        "category": "Japanese",
        "address": "서울 용산구 한남대로 136",
        "latitude": 37.5360, "longitude": 127.0020,
        "price_range": 3, "rating": 4.6,
        "description": "한남동의 숨은 스시 오마카세. 제철 재료로 구성된 코스가 매달 바뀝니다.",
        "phone": "02-793-8855",
    },
    {
        "name": "건대 초밥",
        "category": "Japanese",
        "address": "서울 광진구 아차산로 200",
        "latitude": 37.5410, "longitude": 127.0680,
        "price_range": 2, "rating": 4.2,
        "description": "건대 대학가의 합리적인 가격의 초밥 전문점. 세트 메뉴 구성이 다양.",
        "phone": "02-449-6655",
    },

    # ── 이탈리안 (12) ──────────────────────────────────────────────────────
    {
        "name": "트라토리아 벨라",
        "category": "Italian",
        "address": "서울 용산구 한남대로 45",
        "latitude": 37.5347, "longitude": 127.0007,
        "price_range": 2, "rating": 4.5,
        "description": "장작불 화덕 피자와 수제 파스타. 나폴리 정통 레시피를 선보입니다.",
        "phone": "02-8901-2345",
    },
    {
        "name": "파스타 프리마",
        "category": "Italian",
        "address": "서울 강남구 압구정로 99",
        "latitude": 37.5270, "longitude": 127.0285,
        "price_range": 3, "rating": 4.6,
        "description": "테이스팅 메뉴와 와인 페어링이 있는 파인 다이닝 이탈리안 레스토랑.",
        "phone": "02-9012-3456",
    },
    {
        "name": "코너 피자리아",
        "category": "Italian",
        "address": "서울 마포구 마포대로 22",
        "latitude": 37.5500, "longitude": 126.9494,
        "price_range": 1, "rating": 4.1,
        "description": "캐주얼한 뉴욕 스타일 피자 슬라이스와 칼초네를 즐길 수 있는 곳.",
        "phone": "02-0123-4567",
    },
    {
        "name": "이태원 이탈리아노",
        "category": "Italian",
        "address": "서울 용산구 이태원로 180",
        "latitude": 37.5345, "longitude": 126.9960,
        "price_range": 2, "rating": 4.4,
        "description": "이탈리아 현지 셰프가 운영하는 정통 이탈리아 레스토랑. 홈메이드 파스타.",
        "phone": "02-796-4422",
    },
    {
        "name": "홍대 파스타",
        "category": "Italian",
        "address": "서울 마포구 와우산로 71",
        "latitude": 37.5570, "longitude": 126.9230,
        "price_range": 1, "rating": 4.2,
        "description": "합리적인 가격의 크리미 파스타와 알리오 올리오. 대학생들의 데이트 맛집.",
        "phone": "02-323-6677",
    },
    {
        "name": "합정 피자",
        "category": "Italian",
        "address": "서울 마포구 합정동 412",
        "latitude": 37.5495, "longitude": 126.9150,
        "price_range": 2, "rating": 4.3,
        "description": "나폴리탄 피자 장인이 만드는 마르게리타와 칼조네. 장작 화덕의 향이 일품.",
        "phone": "02-336-8833",
    },
    {
        "name": "한남 리조또",
        "category": "Italian",
        "address": "서울 용산구 이태원로55나길 22",
        "latitude": 37.5370, "longitude": 127.0050,
        "price_range": 2, "rating": 4.5,
        "description": "해산물 리조또와 버섯 리조또가 시그니처. 와인 리스트도 훌륭합니다.",
        "phone": "02-793-2211",
    },
    {
        "name": "성수 파스타바",
        "category": "Italian",
        "address": "서울 성동구 뚝섬로 273",
        "latitude": 37.5450, "longitude": 127.0520,
        "price_range": 2, "rating": 4.4,
        "description": "인더스트리얼 분위기의 성수 파스타 바. 오픈 키친에서 보이는 조리 과정도 볼거리.",
        "phone": "02-465-9988",
    },
    {
        "name": "강남 이탈리안",
        "category": "Italian",
        "address": "서울 강남구 도산대로 313",
        "latitude": 37.5250, "longitude": 127.0340,
        "price_range": 3, "rating": 4.6,
        "description": "모던 이탈리안 파인 다이닝. 계절 트러플 요리가 특히 유명합니다.",
        "phone": "02-544-5522",
    },
    {
        "name": "압구정 화덕피자",
        "category": "Italian",
        "address": "서울 강남구 압구정로 78",
        "latitude": 37.5280, "longitude": 127.0270,
        "price_range": 2, "rating": 4.3,
        "description": "400도 화덕에서 90초 만에 구워내는 나폴리탄 피자. 쫀득한 도우가 특징.",
        "phone": "02-548-7733",
    },
    {
        "name": "신사 리스토란테",
        "category": "Italian",
        "address": "서울 강남구 가로수길 44",
        "latitude": 37.5195, "longitude": 127.0215,
        "price_range": 3, "rating": 4.7,
        "description": "가로수길의 럭셔리 이탈리안 파인 다이닝. 파스타, 리조또, 메인 코스 구성.",
        "phone": "02-541-1188",
    },
    {
        "name": "인사동 파스타",
        "category": "Italian",
        "address": "서울 종로구 인사동길 33",
        "latitude": 37.5738, "longitude": 126.9845,
        "price_range": 2, "rating": 4.2,
        "description": "인사동 문화 거리의 여유로운 이탈리안 레스토랑. 전시 관람 후 방문하기 좋은 곳.",
        "phone": "02-735-4455",
    },

    # ── 중식 (8) ──────────────────────────────────────────────────────────
    {
        "name": "드래곤 팰리스",
        "category": "Chinese",
        "address": "인천 중구 차이나타운로 10",
        "latitude": 37.4756, "longitude": 126.6175,
        "price_range": 2, "rating": 4.3,
        "description": "딤섬과 광둥 요리 전문점. 활기찬 분위기에서 다양한 중식을 즐길 수 있습니다.",
        "phone": "032-333-4444",
    },
    {
        "name": "쓰촨 마라탕",
        "category": "Chinese",
        "address": "서울 중구 을지로3가",
        "latitude": 37.5662, "longitude": 126.9937,
        "price_range": 2, "rating": 4.2,
        "description": "정통 쓰촨 마라탕과 마라샹궈. 매운 맛을 좋아하는 분께 추천합니다.",
        "phone": "02-3344-5566",
    },
    {
        "name": "연남 마라샹궈",
        "category": "Chinese",
        "address": "서울 마포구 연남로 85",
        "latitude": 37.5600, "longitude": 126.9250,
        "price_range": 2, "rating": 4.4,
        "description": "재료를 직접 골라 볶는 마라샹궈. 매운 정도를 조절할 수 있어 인기 만점.",
        "phone": "02-337-8877",
    },
    {
        "name": "강남 딤섬",
        "category": "Chinese",
        "address": "서울 강남구 테헤란로 501",
        "latitude": 37.5060, "longitude": 127.0530,
        "price_range": 2, "rating": 4.3,
        "description": "홍콩 현지 레시피의 딤섬 전문점. 하가우, 샤오마이, 춘권 등 다양한 딤섬.",
        "phone": "02-569-2211",
    },
    {
        "name": "이태원 중화요리",
        "category": "Chinese",
        "address": "서울 용산구 이태원로 166",
        "latitude": 37.5340, "longitude": 126.9930,
        "price_range": 2, "rating": 4.2,
        "description": "베이징 오리구이와 북경 요리 전문. 전통 중국 인테리어가 분위기를 더합니다.",
        "phone": "02-795-3322",
    },
    {
        "name": "종로 짜장면",
        "category": "Chinese",
        "address": "서울 종로구 종로 218",
        "latitude": 37.5700, "longitude": 126.9910,
        "price_range": 1, "rating": 4.0,
        "description": "50년 전통의 옛날 짜장면 전문점. 춘장을 직접 볶은 진한 짜장이 특징.",
        "phone": "02-742-5577",
    },
    {
        "name": "건대 양꼬치",
        "category": "Chinese",
        "address": "서울 광진구 자양로 128",
        "latitude": 37.5395, "longitude": 127.0750,
        "price_range": 1, "rating": 4.3,
        "description": "숯불에 구운 양꼬치와 양갈비. 고수와 커민 향이 어우러진 중국식 양 요리.",
        "phone": "02-458-9944",
    },
    {
        "name": "홍대 마라탕",
        "category": "Chinese",
        "address": "서울 마포구 홍익로 6길 29",
        "latitude": 37.5565, "longitude": 126.9235,
        "price_range": 1, "rating": 4.2,
        "description": "직접 선택하는 재료로 만드는 개인 맞춤 마라탕. 얼얼한 맛이 매력입니다.",
        "phone": "02-326-4488",
    },

    # ── 양식/아메리칸 (8) ─────────────────────────────────────────────────
    {
        "name": "더 스모크하우스",
        "category": "American",
        "address": "서울 마포구 홍대입구 55",
        "latitude": 37.5567, "longitude": 126.9248,
        "price_range": 2, "rating": 4.3,
        "description": "텍사스 스타일 브리스킷, 립, 수제 맥주를 한 번에 즐길 수 있는 BBQ 레스토랑.",
        "phone": "02-6677-8899",
    },
    {
        "name": "버거앤코",
        "category": "American",
        "address": "서울 성동구 성수동 200",
        "latitude": 37.5444, "longitude": 127.0557,
        "price_range": 1, "rating": 4.2,
        "description": "스매시버거, 감자튀김, 밀크쉐이크를 레트로 다이너 분위기에서.",
        "phone": "02-7788-9900",
    },
    {
        "name": "이태원 스테이크",
        "category": "American",
        "address": "서울 용산구 이태원로 183",
        "latitude": 37.5350, "longitude": 126.9945,
        "price_range": 3, "rating": 4.6,
        "description": "미국산 USDA 프라임 스테이크 전문점. 드라이에이징 안심과 등심이 시그니처.",
        "phone": "02-797-5544",
    },
    {
        "name": "홍대 브런치",
        "category": "American",
        "address": "서울 마포구 잔다리로 33",
        "latitude": 37.5540, "longitude": 126.9220,
        "price_range": 2, "rating": 4.3,
        "description": "에그 베네딕트, 팬케이크, 아보카도 토스트. 주말 브런치로 인기 있는 카페 레스토랑.",
        "phone": "02-324-7744",
    },
    {
        "name": "강남 아메리칸 BBQ",
        "category": "American",
        "address": "서울 강남구 강남대로 262",
        "latitude": 37.5020, "longitude": 127.0260,
        "price_range": 2, "rating": 4.2,
        "description": "스모키한 풀드포크와 베이비백 립. 수제 BBQ 소스의 달콤 짭조름한 맛.",
        "phone": "02-565-8811",
    },
    {
        "name": "한남 레스토랑",
        "category": "American",
        "address": "서울 용산구 한남대로 127",
        "latitude": 37.5360, "longitude": 127.0030,
        "price_range": 3, "rating": 4.5,
        "description": "캐주얼 파인 다이닝 스타일의 아메리칸 레스토랑. 버거부터 스테이크까지.",
        "phone": "02-792-6633",
    },
    {
        "name": "성수 핫도그",
        "category": "American",
        "address": "서울 성동구 성수이로7나길 45",
        "latitude": 37.5450, "longitude": 127.0500,
        "price_range": 1, "rating": 4.0,
        "description": "미국 스타일 수제 핫도그와 크라프트 맥주. 성수 힙한 가게의 필수 코스.",
        "phone": "02-462-4477",
    },
    {
        "name": "합정 브런치",
        "category": "American",
        "address": "서울 마포구 월드컵로1길 20",
        "latitude": 37.5500, "longitude": 126.9140,
        "price_range": 2, "rating": 4.2,
        "description": "느긋하게 즐기는 주말 브런치. 다양한 에그 메뉴와 신선한 과일 플레이트.",
        "phone": "02-337-5522",
    },

    # ── 프렌치 (5) ─────────────────────────────────────────────────────────
    {
        "name": "비스트로 루미에르",
        "category": "French",
        "address": "서울 강남구 신사동 515",
        "latitude": 37.5256, "longitude": 127.0238,
        "price_range": 3, "rating": 4.7,
        "description": "덕 콩피와 수플레가 있는 정통 프렌치 비스트로. 촛불 인테리어로 로맨틱한 분위기.",
        "phone": "02-1122-3344",
    },
    {
        "name": "카페 드 파리",
        "category": "French",
        "address": "서울 강남구 가로수길 34",
        "latitude": 37.5199, "longitude": 127.0221,
        "price_range": 2, "rating": 4.4,
        "description": "크레페, 키슈, 애프터눈 티를 즐길 수 있는 캐주얼 프렌치 카페.",
        "phone": "02-2233-4455",
    },
    {
        "name": "한남 브라세리",
        "category": "French",
        "address": "서울 용산구 이태원로 248",
        "latitude": 37.5345, "longitude": 127.0010,
        "price_range": 3, "rating": 4.6,
        "description": "파리지앵 스타일의 브라세리. 스테이크 타르타르와 부야베스가 시그니처.",
        "phone": "02-794-3388",
    },
    {
        "name": "이태원 프렌치",
        "category": "French",
        "address": "서울 용산구 이태원로 200",
        "latitude": 37.5352, "longitude": 126.9948,
        "price_range": 2, "rating": 4.4,
        "description": "부담 없이 즐기는 프렌치 비스트로. 프렌치 어니언 수프와 크루아상 샌드위치.",
        "phone": "02-796-2255",
    },
    {
        "name": "청담 프렌치",
        "category": "French",
        "address": "서울 강남구 청담동 133",
        "latitude": 37.5205, "longitude": 127.0480,
        "price_range": 3, "rating": 4.8,
        "description": "미슐랭 스타 출신 셰프의 모던 프렌치 오마카세. 코스별 와인 페어링 추천.",
        "phone": "02-546-9966",
    },

    # ── 태국 (5) ──────────────────────────────────────────────────────────
    {
        "name": "타이 가든",
        "category": "Thai",
        "address": "서울 용산구 이태원동 120",
        "latitude": 37.5358, "longitude": 126.9940,
        "price_range": 2, "rating": 4.4,
        "description": "향긋한 태국 커리, 팟타이, 망고 찹쌀밥을 맛볼 수 있는 태국 음식 전문점.",
        "phone": "02-4455-6677",
    },
    {
        "name": "이태원 타이",
        "category": "Thai",
        "address": "서울 용산구 이태원로 158",
        "latitude": 37.5345, "longitude": 126.9920,
        "price_range": 2, "rating": 4.3,
        "description": "태국 현지 재료로 만든 정통 태국 요리. 똠얌꿍과 그린 커리가 특히 인기.",
        "phone": "02-793-6611",
    },
    {
        "name": "홍대 팟타이",
        "category": "Thai",
        "address": "서울 마포구 홍익로 10",
        "latitude": 37.5575, "longitude": 126.9250,
        "price_range": 1, "rating": 4.2,
        "description": "고수 향 가득한 정통 팟타이 전문점. 해산물과 닭고기 옵션 모두 가능.",
        "phone": "02-326-8822",
    },
    {
        "name": "강남 타이",
        "category": "Thai",
        "address": "서울 강남구 역삼동 737",
        "latitude": 37.5010, "longitude": 127.0390,
        "price_range": 2, "rating": 4.3,
        "description": "방콕의 길거리 음식을 세련되게 재해석한 모던 태국 레스토랑.",
        "phone": "02-556-7733",
    },
    {
        "name": "연남 태국",
        "category": "Thai",
        "address": "서울 마포구 동교로 249",
        "latitude": 37.5605, "longitude": 126.9290,
        "price_range": 2, "rating": 4.4,
        "description": "연남동 감성의 태국 레스토랑. 카오팟, 마사만 커리 등 다양한 메뉴.",
        "phone": "02-334-4411",
    },

    # ── 인도 (4) ──────────────────────────────────────────────────────────
    {
        "name": "스파이스 루트",
        "category": "Indian",
        "address": "서울 용산구 이태원로 45",
        "latitude": 37.5345, "longitude": 126.9950,
        "price_range": 2, "rating": 4.4,
        "description": "북인도 커리, 난, 탄두리 요리 전문점. 이태원 인도 음식의 대표 맛집.",
        "phone": "02-8899-0011",
    },
    {
        "name": "이태원 인도",
        "category": "Indian",
        "address": "서울 용산구 이태원로 173",
        "latitude": 37.5347, "longitude": 126.9935,
        "price_range": 2, "rating": 4.3,
        "description": "인도 현지인이 운영하는 정통 인도 레스토랑. 버터 치킨과 팔락 파니르가 유명.",
        "phone": "02-794-8822",
    },
    {
        "name": "홍대 탄두리",
        "category": "Indian",
        "address": "서울 마포구 성미산로 28",
        "latitude": 37.5580, "longitude": 126.9270,
        "price_range": 2, "rating": 4.2,
        "description": "탄두르 화덕에서 구운 닭고기와 치즈 난. 채식주의자를 위한 메뉴도 다양.",
        "phone": "02-322-6699",
    },
    {
        "name": "강남 인도",
        "category": "Indian",
        "address": "서울 강남구 테헤란로 211",
        "latitude": 37.5040, "longitude": 127.0430,
        "price_range": 2, "rating": 4.1,
        "description": "강남 직장인들의 인기 인도 레스토랑. 점심 뷔페가 특히 가성비 있습니다.",
        "phone": "02-567-3377",
    },

    # ── 멕시칸 (4) ────────────────────────────────────────────────────────
    {
        "name": "카사 멕시카나",
        "category": "Mexican",
        "address": "서울 마포구 망원동 77",
        "latitude": 37.5556, "longitude": 126.9049,
        "price_range": 1, "rating": 4.1,
        "description": "타코, 부리토, 마가리타를 활기찬 칸티나 분위기에서 즐길 수 있습니다.",
        "phone": "02-9900-1122",
    },
    {
        "name": "이태원 타코",
        "category": "Mexican",
        "address": "서울 용산구 이태원로 196",
        "latitude": 37.5353, "longitude": 126.9944,
        "price_range": 1, "rating": 4.3,
        "description": "직접 만든 옥수수 토르티야 타코 전문점. 알파스토르와 카르니타스가 인기.",
        "phone": "02-792-4455",
    },
    {
        "name": "홍대 부리토",
        "category": "Mexican",
        "address": "서울 마포구 어울마당로 40",
        "latitude": 37.5575, "longitude": 126.9260,
        "price_range": 1, "rating": 4.1,
        "description": "큼직한 부리토 볼과 나초. 할라피뇨와 살사로 취향대로 맛을 조절합니다.",
        "phone": "02-324-5577",
    },
    {
        "name": "강남 멕시칸",
        "category": "Mexican",
        "address": "서울 강남구 역삼동 822",
        "latitude": 37.5000, "longitude": 127.0350,
        "price_range": 2, "rating": 4.2,
        "description": "모던 멕시칸 레스토랑. 과카몰리, 케사디야, 엔칠라다 등 다양한 메뉴.",
        "phone": "02-554-6633",
    },

    # ── 지중해 (4) ────────────────────────────────────────────────────────
    {
        "name": "올리비아",
        "category": "Mediterranean",
        "address": "서울 영등포구 여의도동 32",
        "latitude": 37.5217, "longitude": 126.9244,
        "price_range": 2, "rating": 4.5,
        "description": "그리스·터키 메제와 신선한 해산물을 야외 테라스에서 즐길 수 있는 지중해 레스토랑.",
        "phone": "02-5566-7788",
    },
    {
        "name": "한남 그리스",
        "category": "Mediterranean",
        "address": "서울 용산구 한남대로 146",
        "latitude": 37.5358, "longitude": 127.0025,
        "price_range": 2, "rating": 4.4,
        "description": "그리스 현지 분위기의 레스토랑. 수블라키, 무사카, 바클라바 등 정통 그리스 요리.",
        "phone": "02-793-1188",
    },
    {
        "name": "이태원 지중해",
        "category": "Mediterranean",
        "address": "서울 용산구 이태원로 177",
        "latitude": 37.5348, "longitude": 126.9937,
        "price_range": 2, "rating": 4.3,
        "description": "레바논, 터키, 그리스 요리를 한 자리에서. 후무스와 팔라펠이 인기 메뉴.",
        "phone": "02-795-3344",
    },
    {
        "name": "강남 지중해",
        "category": "Mediterranean",
        "address": "서울 강남구 선릉로 825",
        "latitude": 37.5080, "longitude": 127.0550,
        "price_range": 3, "rating": 4.5,
        "description": "모던 지중해 파인 다이닝. 해산물 플래터와 오리 콩피가 시그니처 메뉴.",
        "phone": "02-567-8899",
    },
]


def run(force: bool = False):
    print("Creating tables...")
    Base.metadata.create_all(bind=engine)

    db = SessionLocal()
    try:
        existing = db.query(Restaurant).count()
        if existing > 0 and not force:
            print(f"Seed already done - {existing} restaurants found. Use --force to re-seed.")
            return

        if force and existing > 0:
            db.query(Restaurant).delete()
            db.commit()
            print(f"Deleted {existing} existing restaurants.")

        restaurants = [Restaurant(**r) for r in SEED_RESTAURANTS]
        db.add_all(restaurants)
        db.commit()
        print(f"Seeded {len(restaurants)} restaurants successfully.")
    finally:
        db.close()


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--force", action="store_true", help="기존 데이터 삭제 후 재시딩")
    args = parser.parse_args()
    run(force=args.force)
